class PlayerEntry:
    def __init__(self, data):
        self.id = data.get("id", None)
        self.joined_time = data.get("joined_time", None)
        self.started_event = data.get("started_event", None)
        self.favourite_team = data.get("favourite_team", None)
        self.player_first_name = data.get("player_first_name", None)
        self.player_last_name = data.get("player_last_name", None)
        self.player_region_id = data.get("player_region_id", None)
        self.player_region_name = data.get("player_region_name", None)
        self.player_region_iso_code_short = data.get("player_region_iso_code_short", None)
        self.player_region_iso_code_long = data.get("player_region_iso_code_long", None)
        self.summary_overall_points = data.get("summary_overall_points", None)
        self.summary_overall_rank = data.get("summary_overall_rank", None)
        self.summary_event_points = data.get("summary_event_points", None)
        self.summary_event_rank = data.get("summary_event_rank", None)
        self.current_event = data.get("current_event", None)
        self.name = data.get("name", None)
        self.name_change_blocked = data.get("name_change_blocked", None)
        self.kit = data.get("kit", None)
        self.last_deadline_bank = data.get("last_deadline_bank", None)
        self.last_deadline_value = data.get("last_deadline_value", None)
        self.last_deadline_total_transfers = data.get("last_deadline_total_transfers", None)
        self.leagues = data.get("leagues", {})